// Export and Share Service
// Provides functionality to export content in various formats and share

interface ExportOptions {
    format: 'pdf' | 'markdown' | 'json' | 'text';
    includeImages?: boolean;
    includeQuiz?: boolean;
}

interface ShareOptions {
    platform: 'twitter' | 'linkedin' | 'whatsapp' | 'copy' | 'native';
    title: string;
    text: string;
    url?: string;
}

export const exportService = {

    // Export lesson plan to different formats
    exportLessonPlan: async (
        data: {
            topic: string;
            summary: string;
            analogy: string;
            keyConcepts: { title: string; description: string }[];
            quiz?: { question: string; options: string[]; correctAnswerIndex: number }[];
        },
        options: ExportOptions
    ): Promise<string | Blob> => {
        switch (options.format) {
            case 'markdown':
                return exportToMarkdown(data);
            case 'json':
                return JSON.stringify(data, null, 2);
            case 'text':
                return exportToText(data);
            case 'pdf':
                return exportToPDF(data);
            default:
                throw new Error('Unsupported format');
        }
    },

    // Share content to various platforms
    share: async (options: ShareOptions): Promise<boolean> => {
        const { platform, title, text, url } = options;
        const shareUrl = url || window.location.href;
        const fullText = `${title}\n\n${text}`;

        switch (platform) {
            case 'native':
                if (navigator.share) {
                    try {
                        await navigator.share({ title, text, url: shareUrl });
                        return true;
                    } catch (err) {
                        console.error('Share failed:', err);
                        return false;
                    }
                }
                // Fallback to copy
                return copyToClipboard(fullText + '\n' + shareUrl);

            case 'twitter':
                const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(shareUrl)}`;
                window.open(twitterUrl, '_blank', 'width=550,height=420');
                return true;

            case 'linkedin':
                const linkedinUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`;
                window.open(linkedinUrl, '_blank', 'width=550,height=420');
                return true;

            case 'whatsapp':
                const whatsappUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(fullText + '\n' + shareUrl)}`;
                window.open(whatsappUrl, '_blank');
                return true;

            case 'copy':
                return copyToClipboard(fullText + '\n' + shareUrl);

            default:
                return false;
        }
    },

    // Download file
    download: (content: string | Blob, filename: string, type: string = 'text/plain') => {
        const blob = content instanceof Blob ? content : new Blob([content], { type });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    },

    // Generate shareable URL with encoded state
    generateShareableUrl: (topic: string, class_: string, subject: string): string => {
        const params = new URLSearchParams({
            topic,
            class: class_,
            subject,
        });
        return `${window.location.origin}?${params.toString()}`;
    },
};

// Helper functions
function exportToMarkdown(data: any): string {
    let md = `# ${data.topic}\n\n`;
    md += `## Summary\n${data.summary}\n\n`;
    md += `## Real-World Analogy\n${data.analogy}\n\n`;
    md += `## Key Concepts\n`;
    data.keyConcepts.forEach((concept: any, i: number) => {
        md += `### ${i + 1}. ${concept.title}\n${concept.description}\n\n`;
    });

    if (data.quiz && data.quiz.length > 0) {
        md += `## Quiz\n`;
        data.quiz.forEach((q: any, i: number) => {
            md += `**Q${i + 1}. ${q.question}**\n`;
            q.options.forEach((opt: string, j: number) => {
                const marker = j === q.correctAnswerIndex ? '✓' : ' ';
                md += `${marker} ${String.fromCharCode(65 + j)}. ${opt}\n`;
            });
            md += '\n';
        });
    }

    md += `\n---\n*Generated by Pictorial - AI-Powered Visual Learning Platform*\n`;
    return md;
}

function exportToText(data: any): string {
    let text = `${data.topic.toUpperCase()}\n${'='.repeat(data.topic.length)}\n\n`;
    text += `SUMMARY\n${'-'.repeat(7)}\n${data.summary}\n\n`;
    text += `REAL-WORLD ANALOGY\n${'-'.repeat(18)}\n${data.analogy}\n\n`;
    text += `KEY CONCEPTS\n${'-'.repeat(12)}\n`;
    data.keyConcepts.forEach((concept: any, i: number) => {
        text += `${i + 1}. ${concept.title}\n   ${concept.description}\n\n`;
    });

    text += `\nGenerated by Pictorial - AI-Powered Visual Learning Platform`;
    return text;
}

function exportToPDF(data: any): string {
    // Generate HTML for PDF printing
    const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${data.topic} - Pictorial</title>
      <style>
        body {
          font-family: Georgia, serif;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px;
          line-height: 1.6;
          color: #1a1a1a;
        }
        h1 { color: #7c3aed; border-bottom: 2px solid #7c3aed; padding-bottom: 10px; }
        h2 { color: #4a5568; margin-top: 30px; }
        h3 { color: #2d3748; }
        .concept { background: #f7f7f7; padding: 15px; margin: 10px 0; border-radius: 8px; }
        .quiz { background: #fff7ed; padding: 15px; margin: 10px 0; border-radius: 8px; }
        .correct { color: #059669; font-weight: bold; }
        .footer { text-align: center; color: #9ca3af; font-size: 12px; margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 20px; }
      </style>
    </head>
    <body>
      <h1>${data.topic}</h1>
      <h2>Summary</h2>
      <p>${data.summary}</p>
      <h2>Real-World Analogy</h2>
      <p>${data.analogy}</p>
      <h2>Key Concepts</h2>
      ${data.keyConcepts.map((c: any, i: number) => `
        <div class="concept">
          <h3>${i + 1}. ${c.title}</h3>
          <p>${c.description}</p>
        </div>
      `).join('')}
      ${data.quiz ? `
        <h2>Quiz</h2>
        ${data.quiz.map((q: any, i: number) => `
          <div class="quiz">
            <p><strong>Q${i + 1}. ${q.question}</strong></p>
            ${q.options.map((opt: string, j: number) => `
              <p class="${j === q.correctAnswerIndex ? 'correct' : ''}">${String.fromCharCode(65 + j)}. ${opt}</p>
            `).join('')}
          </div>
        `).join('')}
      ` : ''}
      <div class="footer">
        <p>Generated by Pictorial - AI-Powered Visual Learning Platform</p>
        <p>https://github.com/captflag/Pictorial</p>
      </div>
    </body>
    </html>
  `;

    // Open in new window for printing
    const printWindow = window.open('', '_blank');
    if (printWindow) {
        printWindow.document.write(html);
        printWindow.document.close();
        printWindow.onload = () => printWindow.print();
    }

    return html;
}

async function copyToClipboard(text: string): Promise<boolean> {
    try {
        if (navigator.clipboard) {
            await navigator.clipboard.writeText(text);
            return true;
        } else {
            // Fallback for older browsers
            const textarea = document.createElement('textarea');
            textarea.value = text;
            document.body.appendChild(textarea);
            textarea.select();
            document.execCommand('copy');
            document.body.removeChild(textarea);
            return true;
        }
    } catch (err) {
        console.error('Copy failed:', err);
        return false;
    }
}

export default exportService;
