import React, { useState, useRef } from 'react';
import { FileText, Printer, Download, Loader2, BookOpen, Sparkles, Search, ChevronRight } from 'lucide-react';
import { generateStudyNotes } from '../services/geminiService';
import { StudyNote } from '../types';
import { SkeletonLoader } from './SkeletonLoader';

interface NotesViewProps {
  initialTopic?: string;
  initialClass?: string;
  initialSubject?: string;
}

export const NotesView: React.FC<NotesViewProps> = ({
  initialTopic = '',
  initialClass = '10',
  initialSubject = 'Science'
}) => {
  const [topic, setTopic] = useState(initialTopic);
  const [selectedClass, setSelectedClass] = useState(initialClass);
  const [selectedSubject, setSelectedSubject] = useState(initialSubject);
  const [notes, setNotes] = useState<StudyNote | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const notesContentRef = useRef<HTMLDivElement>(null);

  const subjects = ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'Science', 'Social Science', 'English', 'Hindi', 'Computer Science'];
  const classes = ['5', '6', '7', '8', '9', '10', '11', '12'];

  const handleGenerate = async () => {
    if (!topic.trim()) return;

    setLoading(true);
    setError(null);

    try {
      const result = await generateStudyNotes(selectedClass, selectedSubject, topic);
      setNotes(result);
    } catch (err) {
      setError('Failed to generate notes. Please try again.');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = async () => {
    if (!notesContentRef.current || !notes) return;

    // Create a printable version
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to download PDF');
      return;
    }

    const content = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${notes.title} - Pictorial Notes</title>
        <style>
          body {
            font-family: 'Georgia', serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px;
            line-height: 1.8;
            color: #1e293b;
          }
          h1 {
            color: #7c3aed;
            border-bottom: 3px solid #7c3aed;
            padding-bottom: 10px;
            margin-bottom: 20px;
          }
          h2 {
            color: #334155;
            margin-top: 30px;
            border-left: 4px solid #7c3aed;
            padding-left: 15px;
          }
          .meta {
            background: #f1f5f9;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 30px;
          }
          .meta p { margin: 5px 0; font-size: 14px; }
          .section-content {
            text-align: justify;
            margin-bottom: 20px;
          }
          .formulas {
            background: #fef3c7;
            padding: 20px;
            border-radius: 8px;
            margin-top: 30px;
          }
          .formulas h3 { color: #92400e; margin-top: 0; }
          .formulas ul { margin: 0; }
          .formulas li { 
            font-family: 'Courier New', monospace;
            margin: 8px 0;
            background: white;
            padding: 8px 12px;
            border-radius: 4px;
          }
          .sources {
            margin-top: 30px;
            padding: 15px;
            background: #f0fdf4;
            border-radius: 8px;
          }
          .sources h4 { color: #166534; margin: 0 0 10px 0; }
          .footer {
            margin-top: 40px;
            text-align: center;
            color: #94a3b8;
            font-size: 12px;
            border-top: 1px solid #e2e8f0;
            padding-top: 20px;
          }
          @media print {
            body { padding: 20px; }
          }
        </style>
      </head>
      <body>
        <h1>${notes.title}</h1>
        
        <div class="meta">
          <p><strong>Subject:</strong> ${notes.subject}</p>
          <p><strong>Class:</strong> ${notes.targetClass}</p>
          <p><strong>Generated by:</strong> Pictorial AI</p>
        </div>

        ${notes.sections.map(section => `
          <h2>${section.heading}</h2>
          <div class="section-content">${section.content.replace(/\n/g, '<br>')}</div>
        `).join('')}

        ${notes.importantFormulas.length > 0 ? `
          <div class="formulas">
            <h3>📐 Important Formulas</h3>
            <ul>
              ${notes.importantFormulas.map(f => `<li>${f}</li>`).join('')}
            </ul>
          </div>
        ` : ''}

        <div class="sources">
          <h4>📚 Reference Sources</h4>
          <p>${notes.sourcesUsed.join(', ')}</p>
        </div>

        <div class="footer">
          <p>Generated by Pictorial - AI-Powered Visual Learning Platform</p>
          <p>https://github.com/captflag/Pictorial</p>
        </div>
      </body>
      </html>
    `;

    printWindow.document.write(content);
    printWindow.document.close();

    // Wait for content to load then print
    printWindow.onload = () => {
      printWindow.print();
    };
  };

  const quickTopics = [
    'Photosynthesis', 'Laws of Motion', 'Chemical Reactions',
    'Cell Structure', 'Quadratic Equations', 'Light Reflection'
  ];

  return (
    <div className="max-w-5xl mx-auto space-y-6 animate-in fade-in">
      {/* Header */}
      <div className="glass-panel p-8 rounded-3xl bg-white border border-slate-200 shadow-xl shadow-slate-200/50">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div className="flex items-center gap-4">
            <div className="w-14 h-14 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center border border-emerald-100">
              <FileText size={28} />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-slate-900">Smart Notes</h2>
              <p className="text-slate-500">AI-Synthesized Study Material from Top Reference Books</p>
            </div>
          </div>

          {notes && (
            <div className="flex gap-2">
              <button
                onClick={handlePrint}
                className="glass-button px-4 py-2 rounded-xl flex items-center gap-2 text-slate-600 hover:text-emerald-600 border border-slate-200"
              >
                <Printer size={18} /> Print
              </button>
              <button
                onClick={handleDownloadPDF}
                className="px-4 py-2 bg-emerald-600 text-white rounded-xl flex items-center gap-2 font-medium hover:bg-emerald-700 transition-colors"
              >
                <Download size={18} /> Download PDF
              </button>
            </div>
          )}
        </div>

        {/* Search Form */}
        <div className="mt-6 space-y-4">
          <div className="flex flex-wrap gap-3">
            <select
              value={selectedClass}
              onChange={(e) => setSelectedClass(e.target.value)}
              className="px-4 py-2 rounded-xl border border-slate-200 bg-white text-slate-700 font-medium focus:ring-2 focus:ring-emerald-200 focus:border-emerald-400"
            >
              {classes.map(c => (
                <option key={c} value={c}>Class {c}</option>
              ))}
            </select>

            <select
              value={selectedSubject}
              onChange={(e) => setSelectedSubject(e.target.value)}
              className="px-4 py-2 rounded-xl border border-slate-200 bg-white text-slate-700 font-medium focus:ring-2 focus:ring-emerald-200 focus:border-emerald-400"
            >
              {subjects.map(s => (
                <option key={s} value={s}>{s}</option>
              ))}
            </select>
          </div>

          <div className="flex gap-3">
            <div className="relative flex-1">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={20} />
              <input
                type="text"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
                placeholder="Enter topic (e.g., Photosynthesis, Newton's Laws...)"
                className="w-full pl-12 pr-4 py-3 rounded-xl border border-slate-200 bg-white text-slate-800 focus:ring-2 focus:ring-emerald-200 focus:border-emerald-400"
              />
            </div>
            <button
              onClick={handleGenerate}
              disabled={loading || !topic.trim()}
              className="px-6 py-3 bg-emerald-600 text-white rounded-xl font-bold flex items-center gap-2 hover:bg-emerald-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
            >
              {loading ? <Loader2 className="animate-spin" size={20} /> : <Sparkles size={20} />}
              Generate
            </button>
          </div>

          {/* Quick Topics */}
          <div className="flex flex-wrap gap-2">
            {quickTopics.map(t => (
              <button
                key={t}
                onClick={() => { setTopic(t); }}
                className="px-3 py-1.5 bg-slate-100 text-slate-600 rounded-full text-sm font-medium hover:bg-emerald-100 hover:text-emerald-700 transition-colors"
              >
                {t}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Error State */}
      {error && (
        <div className="bg-red-50 text-red-700 p-4 rounded-xl border border-red-200">
          {error}
        </div>
      )}

      {/* Loading State */}
      {loading && (
        <div className="bg-white rounded-xl shadow-lg border border-slate-200 p-12">
          <SkeletonLoader variant="text" count={3} />
        </div>
      )}

      {/* Notes Content */}
      {notes && !loading && (
        <div
          ref={notesContentRef}
          className="bg-white min-h-[500px] rounded-xl shadow-lg border border-slate-200 relative print:shadow-none print:border-none"
        >
          <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-emerald-400 to-teal-400 rounded-t-xl print:hidden"></div>

          <div className="p-8 md:p-12">
            {/* Title & Meta */}
            <h1 className="text-3xl font-extrabold text-slate-900 mb-4">{notes.title}</h1>
            <div className="flex flex-wrap gap-3 mb-8">
              <span className="px-3 py-1 bg-emerald-100 text-emerald-700 rounded-full text-sm font-medium">
                {notes.subject}
              </span>
              <span className="px-3 py-1 bg-slate-100 text-slate-600 rounded-full text-sm font-medium">
                Class {notes.targetClass}
              </span>
              <span className="px-3 py-1 bg-violet-100 text-violet-700 rounded-full text-sm font-medium">
                📚 {notes.sourcesUsed.join(', ')}
              </span>
            </div>

            {/* Sections */}
            <div className="space-y-8">
              {notes.sections.map((section, i) => (
                <div key={i} className="border-l-4 border-emerald-400 pl-6">
                  <h2 className="text-xl font-bold text-slate-800 mb-3">{section.heading}</h2>
                  <div className="prose prose-slate max-w-none">
                    {section.content.split('\n').map((para, j) => (
                      <p key={j} className="text-slate-600 leading-relaxed mb-3">{para}</p>
                    ))}
                  </div>
                </div>
              ))}
            </div>

            {/* Formulas */}
            {notes.importantFormulas.length > 0 && (
              <div className="mt-10 p-6 bg-amber-50 rounded-2xl border border-amber-200">
                <h3 className="text-lg font-bold text-amber-800 mb-4 flex items-center gap-2">
                  📐 Important Formulas
                </h3>
                <ul className="space-y-2">
                  {notes.importantFormulas.map((formula, i) => (
                    <li key={i} className="font-mono bg-white px-4 py-2 rounded-lg text-slate-700 border border-amber-100">
                      {formula}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Empty State */}
      {!notes && !loading && (
        <div className="bg-white min-h-[400px] rounded-xl shadow-lg border border-slate-200 p-12 relative flex items-center justify-center">
          <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-emerald-400 to-teal-400 rounded-t-xl"></div>
          <div className="text-center">
            <div className="w-20 h-20 bg-slate-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <BookOpen size={40} className="text-slate-300" />
            </div>
            <h3 className="text-xl font-bold text-slate-700 mb-2">Generate Study Notes</h3>
            <p className="text-slate-500 max-w-md">
              Enter a topic above to generate comprehensive study notes synthesized from top reference books like RD Sharma, HC Verma, and Pradeep's.
            </p>
          </div>
        </div>
      )}
    </div>
  );
};